version: "3.6"

services:
  backend:
    image: mediacloudai/ex_backend:devel
    volumes:
      - ${PWD}/dash:/dash
    ports:
      - ${BACKEND_PORT}:80
    environment:
      APP_LABEL: "${APP_LABEL}"
      APP_LOGO: "${APP_LOGO}"
      APP_COMPANY_LOGO: "${APP_COMPANY_LOGO}"
      APP_COMPANY: "${APP_COMPANY}"
      APP_IDENTIFIER: "${APP_IDENTIFIER}"

      PORT: 80
      SSL: "${BACKEND_SSL}"

      SENDGRID_API_KEY: "${SENDGRID_API_KEY}"

      DATABASE_URL: "ecto://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_HOSTNAME}:${DATABASE_PORT}/${DATABASE_NAME}?pool_size=10"
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_PORT: "${DATABASE_PORT}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      DATABASE_USERNAME: "${DATABASE_USERNAME}"
      DATABASE_HOSTNAME: "${DATABASE_HOSTNAME}"

      AMQP_HOSTNAME: "${AMQP_HOSTNAME}"
      AMQP_PORT: "${AMQP_PORT}"
      AMQP_MANAGEMENT_PORT: "${AMQP_MANAGEMENT_PORT}"
      AMQP_USERNAME: "${AMQP_USERNAME}"
      AMQP_PASSWORD: "${AMQP_PASSWORD}"
      AMQP_VHOST: "${AMQP_VHOST}"

      WORK_DIR: "/data"
      ROOT_DASH_CONTENT: "/dash"
      
      ROOT_EMAIL: "${ROOT_EMAIL}"
      ROOT_PASSWORD: "${ROOT_PASSWORD}"
      HOSTNAME: "${APP_DNS}"
    labels:
      - "traefik.frontend.entryPoints=http"
      - "traefik.default.protocol=http"
      - "traefik.docker.network=mediacloudai_global"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:backend.media-cloud.ai"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.enable=true"
    networks:
      - mediacloudai_global
      - backend
    depends_on:
      - database

  database:
    image: "postgres:9.6.1"
    environment:
      POSTGRES_USER: "${DATABASE_USERNAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_NAME}"
    labels:
      - "traefik.enable=false"
    networks:
      - backend

networks:
  backend:
    driver: bridge
  mediacloudai_global:
    external: true
