---

version: "3.6"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200
    networks:
      - mediacloudai_global

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    ports:
      - 3000:3000
    user: "0"
    networks:
      - mediacloudai_global

  kibana:
    image: kibana:${KIBANA_VERSION}
    ports:
      - 5601:5601
    networks:
      - mediacloudai_global

networks:
  backbone:
    driver: bridge
  mediacloudai_global:
    external: true
