---

version: "3.6"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
      - "discovery.type=single-node"
    expose:
      - 9200
    ports:
      - 9200:9200
    networks:
      - mediacloudai_global

  grafana:
    image: grafana/grafana:6.5.3
    ports:
      - 3000:3000
    user: "0"
    networks:
      - mediacloudai_global

  kibana:
    image: kibana:7.2.0
    ports:
      - 5601:5601
    networks:
      - mediacloudai_global

networks:
  backbone:
    driver: bridge
  mediacloudai_global:
    external: true
