---

version: "3.6"

services:
  minio:
    image: ${MINIO_IMAGE}:${MINIO_VERSION}
    volumes:
      - ${PWD}/storage-mca:/data
    ports:
      - 9001:9000
    entrypoint:
      - minio
      - server
      - /data
    environment:
      MINIO_SECRET_KEY: "mediacloudai"
      MINIO_ACCESS_KEY: "mediacloudai"
      MINIO_CERT_PASSWD: "mediacloudai"
    networks:
      - mediacloudai_global
      - storage-mca

  nginx_vod:
    image: ${NGINXVODMODULE_IMAGE}:${NGINXVODMODULE_VERSION}
    volumes:
      - ${PWD}/storage-mca:/data/
    ports:
      - 8081:80
    labels:
      - "traefik.enable=false"
    environment:
      EXPOSED_ENTRY_POINT: "${VOD_EXPOSED_DOMAIN_NAME}"
    networks:
      - mediacloudai_global
      - storage-mca

  http_nginx:
    image: ${HTTP_NGINX_IMAGE}:${HTTP_NGINX_VERSION}
    volumes:
      - ${PWD}/storage-mca:/data/
    ports:
      - "8082:80"
    labels:
      - "traefik.enable=false"
    networks:
      - mediacloudai_global
      - storage-mca

  ftp_vsftpd:
    image: ${FTP_SERVER_IMAGE}:${FTP_SERVER_VERSION}
    volumes:
      - ${PWD}/storage-mca:/data
    ports:
      - "9021:21"
      - "21000-21010:21000-21010"
    labels:
      - "traefik.enable=false"
    environment:
      - "USERS=mediacloudai|mEd1aCl0uda1|/data"
    networks:
      - mediacloudai_global
      - storage-mca

networks:
  storage-mca:
    driver: bridge
  mediacloudai_global:
    external: true
