---

version: "3.6"

services:
  minio:
    image: minio/minio:RELEASE.2019-10-02T21-19-38Z
    volumes:
      - ${PWD}/storage-mca:/data
    ports:
      - 9001:9000
    entrypoint:
      - minio
      - server
      - /data
    environment:
      MINIO_SECRET_KEY: "mediacloudai"
      MINIO_ACCESS_KEY: "mediacloudai"
      MINIO_CERT_PASSWD: "mediacloudai"
    networks:
      - mediacloudai_global
      - storage-mca

  nginx_vod:
    image: mediacloudai/nginx_vod_module
    volumes:
      - ${PWD}/storage-mca:/data/
    ports:
      - 8081:80
    labels:
      - "traefik.enable=false"
    environment:
      EXPOSED_ENTRY_POINT: "${VOD_EXPOSED_DOMAIN_NAME}"
    networks:
      - mediacloudai_global
      - storage-mca

networks:
  storage-mca:
    driver: bridge
  mediacloudai_global:
    external: true
