scrape_configs:
- job_name: rabbitmq_metrics_grabber
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http

  static_configs:
    - targets: [ 'rabbitmq:15692' ]
      labels:
        name: rabbitmq
