---

version: "3.6"

services:
  rabbitmq:
    build:
      context: .
      args:
        - RABBITMQ_IMAGE=${RABBITMQ_IMAGE}
        - RABBITMQ_VERSION=${RABBITMQ_VERSION}
    networks:
      - backbone
      - mediacloudai_global
    ports:
      - 5678:5672
      - 15678:15672
    labels:
      - "traefik.enable=false"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

networks:
  backbone:
    driver: bridge
  mediacloudai_global:
    external: true
