version: "3.6"

services:
  rabbitmq:
    image: "rabbitmq:3.7.7-management"
    networks:
      - backbone
      - mediacloudai_global
    labels:
      - "traefik.enable=false"
    environment:
      RABBITMQ_DEFAULT_USER: ${AMQP_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${AMQP_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${AMQP_VHOST}

networks:
  backbone:
    driver: bridge
  mediacloudai_global:
    external: true
