---

version: "3.6"

services:
  rabbitmq:
    build:
      context: .
      args:
        - RABBITMQ_IMAGE=${RABBITMQ_IMAGE}
        - RABBITMQ_VERSION=${RABBITMQ_VERSION}
    networks:
      - backbone
      - mediacloudai_global
    ports:
      - 5678:5672
      - 15678:15672
      - 5677:5671
      - 15677:15671
    labels:
      - "traefik.enable=false"
    volumes:
      - ./config:/etc/rabbitmq
    environment:
      RABBITMQ_SSL_CACERTFILE:
      RABBITMQ_SSL_CERTFILE:
      RABBITMQ_SSL_DEPTH:
      RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT:
      RABBITMQ_SSL_KEYFILE:
      RABBITMQ_SSL_VERIFY:
      RABBITMQ_MANAGEMENT_SSL_CACERTFILE:
      RABBITMQ_MANAGEMENT_SSL_CERTFILE:
      RABBITMQ_MANAGEMENT_SSL_DEPTH:
      RABBITMQ_MANAGEMENT_SSL_FAIL_IF_NO_PEER_CERT:
      RABBITMQ_MANAGEMENT_SSL_KEYFILE:
      RABBITMQ_MANAGEMENT_SSL_VERIFY:
      RABBITMQ_DEFAULT_USER: ${AMQP_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${AMQP_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${AMQP_VIRTUAL_HOST}

networks:
  backbone:
    driver: bridge
  mediacloudai_global:
    external: true
