---

version: "3.6"

services:
  rabbitmq:
    image: "rabbitmq:3.7.7-management"
    networks:
      - backbone
      - mediacloudai_global
    ports:
      - 5678:5672
      - 15678:15672
    labels:
      - "traefik.enable=false"
    environment:
      RABBITMQ_DEFAULT_USER: ${AMQP_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${AMQP_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${AMQP_VHOST}

  vault:
    image: "vault:1.3.0"
    networks:
      - backbone
      - mediacloudai_global
    ports:
      - 8201:8201
    labels:
      - "traefik.enable=false"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_DEV_ROOT_TOKEN_ID}
    cap_add:
      - IPC_LOCK
    volumes:
      - ${PWD}/vault:/vault/

networks:
  backbone:
    driver: bridge
  mediacloudai_global:
    external: true
