version: "3.6"

services:
  rs_tranfer_worker:
    image: mediacloudai/rs_tranfer_worker:latest
    volumes:
      - ${PWD}/data:/data
    environment:
      AMQP_QUEUE: "job_ftp"
      AMQP_HOSTNAME: "${AMQP_HOSTNAME}"
      AMQP_PORT: "${AMQP_PORT}"
      AMQP_MANAGEMENT_PORT: "${AMQP_MANAGEMENT_PORT}"
      AMQP_USERNAME: "${AMQP_USERNAME}"
      AMQP_PASSWORD: "${AMQP_PASSWORD}"
      AMQP_VHOST: "${AMQP_VHOST}"
      AMQP_TLS: "${AMQP_TLS}"
      RUST_LOG: "debug"
      BACKEND_PASSWORD: "${ROOT_PASSWORD}"
      BACKEND_HOSTNAME: "http://${HOSTNAME}/api"
      BACKEND_USERNAME: "${ROOT_EMAIL}"
    networks:
      - mediacloudai_global
      - workers

networks:
  workers:
    driver: bridge
  mediacloudai_global:
    external: true
