---

version: "3.6"

services:
  command_line:
    image: mediacloudai/rs_command_line_worker:latest
    volumes:
      - ${PWD}/data:/data
    environment:
      AMQP_QUEUE: "job_command_line"
      AMQP_HOSTNAME: "${AMQP_HOSTNAME}"
      AMQP_PORT: "${AMQP_PORT}"
      AMQP_MANAGEMENT_PORT: "${AMQP_MANAGEMENT_PORT}"
      AMQP_USERNAME: "${AMQP_USERNAME}"
      AMQP_PASSWORD: "${AMQP_PASSWORD}"
      AMQP_VHOST: "${AMQP_VHOST}"
      AMQP_TLS: "${AMQP_TLS}"
      RUST_LOG: "info"
      BACKEND_PASSWORD: "${ROOT_PASSWORD}"
      BACKEND_HOSTNAME: "http://${HOSTNAME}:${BACKEND_PORT}/api"
      BACKEND_USERNAME: "${ROOT_EMAIL}"
    networks:
      - mediacloudai_global
      - workers

  file_system:
    image: mediacloudai/rs_file_system_worker:v0.2.1
    volumes:
      - ${PWD}/data:/data
    environment:
      AMQP_QUEUE: "job_file_system"
      AMQP_HOSTNAME: "${AMQP_HOSTNAME}"
      AMQP_PORT: "${AMQP_PORT}"
      AMQP_MANAGEMENT_PORT: "${AMQP_MANAGEMENT_PORT}"
      AMQP_USERNAME: "${AMQP_USERNAME}"
      AMQP_PASSWORD: "${AMQP_PASSWORD}"
      AMQP_VHOST: "${AMQP_VHOST}"
      AMQP_TLS: "${AMQP_TLS}"
      RUST_LOG: "info"
      BACKEND_PASSWORD: "${ROOT_PASSWORD}"
      BACKEND_HOSTNAME: "http://${HOSTNAME}:${BACKEND_PORT}/api"
      BACKEND_USERNAME: "${ROOT_EMAIL}"
    networks:
      - mediacloudai_global
      - workers

  transfer:
    image: mediacloudai/rs_transfer_worker:v0.1.2
    volumes:
      - ${PWD}/data:/data
    environment:
      AMQP_QUEUE: "job_transfer"
      AMQP_HOSTNAME: "${AMQP_HOSTNAME}"
      AMQP_PORT: "${AMQP_PORT}"
      AMQP_MANAGEMENT_PORT: "${AMQP_MANAGEMENT_PORT}"
      AMQP_USERNAME: "${AMQP_USERNAME}"
      AMQP_PASSWORD: "${AMQP_PASSWORD}"
      AMQP_VHOST: "${AMQP_VHOST}"
      AMQP_TLS: "${AMQP_TLS}"
      RUST_LOG: "info"
      BACKEND_PASSWORD: "${ROOT_PASSWORD}"
      BACKEND_HOSTNAME: "http://${HOSTNAME}:${BACKEND_PORT}/api"
      BACKEND_USERNAME: "${ROOT_EMAIL}"
    networks:
      - mediacloudai_global
      - workers

  ffmpeg:
    image: mediacloudai/rs_ffmpeg_worker:v0.0.1
    volumes:
      - ${PWD}/data:/data
    environment:
      AMQP_QUEUE: "job_ffmpeg"
      AMQP_HOSTNAME: "${AMQP_HOSTNAME}"
      AMQP_PORT: "${AMQP_PORT}"
      AMQP_MANAGEMENT_PORT: "${AMQP_MANAGEMENT_PORT}"
      AMQP_USERNAME: "${AMQP_USERNAME}"
      AMQP_PASSWORD: "${AMQP_PASSWORD}"
      AMQP_VHOST: "${AMQP_VHOST}"
      AMQP_TLS: "${AMQP_TLS}"
      RUST_LOG: "info"
    networks:
      - mediacloudai_global
      - workers

networks:
  workers:
    driver: bridge
  mediacloudai_global:
    external: true
