---

version: "3.6"

services:
  command_line:
    image: mediacloudai/rs_command_line_worker:latest
    volumes:
      - ${PWD}/data:/data
    environment:
      AMQP_QUEUE: "job_command_line"
      AMQP_HOSTNAME: "${AMQP_HOSTNAME}"
      AMQP_PORT: "${AMQP_PORT}"
      AMQP_MANAGEMENT_PORT: "${AMQP_MANAGEMENT_PORT}"
      AMQP_USERNAME: "${AMQP_USERNAME}"
      AMQP_PASSWORD: "${AMQP_PASSWORD}"
      AMQP_VHOST: "${AMQP_VHOST}"
      AMQP_TLS: "${AMQP_TLS}"
      RUST_LOG: "info"
      BACKEND_HOSTNAME: "${BACKEND_HOSTNAME}/api"
      BACKEND_PASSWORD: "${BACKEND_PASSWORD}"
      BACKEND_USERNAME: "${BACKEND_EMAIL}"
    networks:
      - mediacloudai_global
      - workers

  file_system:
    image: mediacloudai/rs_file_system_worker:v0.2.1
    volumes:
      - ${PWD}/data:/data
    environment:
      AMQP_QUEUE: "job_file_system"
      AMQP_HOSTNAME: "${AMQP_HOSTNAME}"
      AMQP_PORT: "${AMQP_PORT}"
      AMQP_MANAGEMENT_PORT: "${AMQP_MANAGEMENT_PORT}"
      AMQP_USERNAME: "${AMQP_USERNAME}"
      AMQP_PASSWORD: "${AMQP_PASSWORD}"
      AMQP_VHOST: "${AMQP_VHOST}"
      AMQP_TLS: "${AMQP_TLS}"
      RUST_LOG: "info"
      BACKEND_HOSTNAME: "${BACKEND_HOSTNAME}/api"
      BACKEND_PASSWORD: "${BACKEND_PASSWORD}"
      BACKEND_USERNAME: "${BACKEND_EMAIL}"
    networks:
      - mediacloudai_global
      - workers

  transfer:
    image: mediacloudai/rs_transfer_worker:v0.1.2
    volumes:
      - ${PWD}/data:/data
    environment:
      AMQP_QUEUE: "job_transfer"
      AMQP_HOSTNAME: "${AMQP_HOSTNAME}"
      AMQP_PORT: "${AMQP_PORT}"
      AMQP_MANAGEMENT_PORT: "${AMQP_MANAGEMENT_PORT}"
      AMQP_USERNAME: "${AMQP_USERNAME}"
      AMQP_PASSWORD: "${AMQP_PASSWORD}"
      AMQP_VHOST: "${AMQP_VHOST}"
      AMQP_TLS: "${AMQP_TLS}"
      RUST_LOG: "info"
      BACKEND_HOSTNAME: "${BACKEND_HOSTNAME}/api"
      BACKEND_PASSWORD: "${BACKEND_PASSWORD}"
      BACKEND_USERNAME: "${BACKEND_EMAIL}"
    networks:
      - mediacloudai_global
      - workers

  ffmpeg:
    image: mediacloudai/rs_ffmpeg_worker:v0.0.1
    volumes:
      - ${PWD}/data:/data
    environment:
      AMQP_QUEUE: "job_ffmpeg"
      AMQP_HOSTNAME: "${AMQP_HOSTNAME}"
      AMQP_PORT: "${AMQP_PORT}"
      AMQP_MANAGEMENT_PORT: "${AMQP_MANAGEMENT_PORT}"
      AMQP_USERNAME: "${AMQP_USERNAME}"
      AMQP_PASSWORD: "${AMQP_PASSWORD}"
      AMQP_VHOST: "${AMQP_VHOST}"
      AMQP_TLS: "${AMQP_TLS}"
      RUST_LOG: "info"
      BACKEND_HOSTNAME: "${BACKEND_HOSTNAME}/api"
      BACKEND_PASSWORD: "${BACKEND_PASSWORD}"
      BACKEND_USERNAME: "${BACKEND_EMAIL}"
    networks:
      - mediacloudai_global
      - workers

  acs:
    image: registry.gitlab.com/mediaio/docker-acs-worker:28b272f
    volumes:
      - ${PWD}/data:/data
    environment:
      AMQP_QUEUE: "job_acs"
      AMQP_HOSTNAME: "${AMQP_HOSTNAME}"
      AMQP_PORT: "${AMQP_PORT}"
      AMQP_MANAGEMENT_PORT: "${AMQP_MANAGEMENT_PORT}"
      AMQP_USERNAME: "${AMQP_USERNAME}"
      AMQP_PASSWORD: "${AMQP_PASSWORD}"
      AMQP_VHOST: "${AMQP_VHOST}"
      AMQP_TLS: "${AMQP_TLS}"
      RUST_LOG: "info"
      BACKEND_HOSTNAME: "${BACKEND_HOSTNAME}/api"
      BACKEND_PASSWORD: "${BACKEND_PASSWORD}"
      BACKEND_USERNAME: "${BACKEND_EMAIL}"
    networks:
      - mediacloudai_global
      - workers

  dash:
    image: mediacloudai/rs_manifest_worker:latest
    volumes:
      - ${PWD}/data:/data
    environment:
      AMQP_QUEUE: "job_dash_manifest"
      AMQP_HOSTNAME: "${AMQP_HOSTNAME}"
      AMQP_PORT: "${AMQP_PORT}"
      AMQP_MANAGEMENT_PORT: "${AMQP_MANAGEMENT_PORT}"
      AMQP_USERNAME: "${AMQP_USERNAME}"
      AMQP_PASSWORD: "${AMQP_PASSWORD}"
      AMQP_VHOST: "${AMQP_VHOST}"
      AMQP_TLS: "${AMQP_TLS}"
      RUST_LOG: "info"
      BACKEND_HOSTNAME: "${BACKEND_HOSTNAME}/api"
      BACKEND_PASSWORD: "${BACKEND_PASSWORD}"
      BACKEND_USERNAME: "${BACKEND_EMAIL}"
      MANIFEST_MODE: "DASH"
    networks:
      - mediacloudai_global
      - workers

  ism:
    image: mediacloudai/rs_manifest_worker:latest
    volumes:
      - ${PWD}/data:/data
    environment:
      AMQP_QUEUE: "job_ism_manifest"
      AMQP_HOSTNAME: "${AMQP_HOSTNAME}"
      AMQP_PORT: "${AMQP_PORT}"
      AMQP_MANAGEMENT_PORT: "${AMQP_MANAGEMENT_PORT}"
      AMQP_USERNAME: "${AMQP_USERNAME}"
      AMQP_PASSWORD: "${AMQP_PASSWORD}"
      AMQP_VHOST: "${AMQP_VHOST}"
      AMQP_TLS: "${AMQP_TLS}"
      RUST_LOG: "info"
      BACKEND_HOSTNAME: "${BACKEND_HOSTNAME}/api"
      BACKEND_PASSWORD: "${BACKEND_PASSWORD}"
      BACKEND_USERNAME: "${BACKEND_EMAIL}"
      MANIFEST_MODE: "ISM"
    networks:
      - mediacloudai_global
      - workers

  stt:
    image: py_speech_to_text_worker
    volumes:
      - ${PWD}/data:/data
    environment:
      AMQP_QUEUE: "job_speech_to_text"
      AMQP_HOSTNAME: "${AMQP_HOSTNAME}"
      AMQP_PORT: "${AMQP_PORT}"
      AMQP_MANAGEMENT_PORT: "${AMQP_MANAGEMENT_PORT}"
      AMQP_USERNAME: "${AMQP_USERNAME}"
      AMQP_PASSWORD: "${AMQP_PASSWORD}"
      AMQP_VHOST: "${AMQP_VHOST}"
      AMQP_TLS: "${AMQP_TLS}"
      RUST_LOG: "info"
      BACKEND_HOSTNAME: "${BACKEND_HOSTNAME}/api"
      BACKEND_PASSWORD: "${BACKEND_PASSWORD}"
      BACKEND_USERNAME: "${BACKEND_EMAIL}"
    networks:
      - mediacloudai_global
      - workers

networks:
  workers:
    driver: bridge
  mediacloudai_global:
    external: true
